module.exports = {
  ignorePatterns: [
    'dist/',
    'lib/',
    'build/',
    'dts/',
    'node_modules/',
    '.eslintrc.js',
    'vite.config.js',
    'jest.config.js',
    'config-overrides.js',
    'mockFile.js',
  ],
  rules: {
    'no-useless-escape': 'warn',
    'no-extra-boolean-cast': 'warn',
    'no-unsafe-optional-chaining': 'warn',
    'import/export': 'warn',
    'import/no-unresolved': 'off',
    'import/no-named-as-default': 'off',
    'import/default': 'off',
    // @typescript-eslint
    '@typescript-eslint/no-floating-promises': 'warn',
    '@typescript-eslint/no-empty-interface': 'warn',
    '@typescript-eslint/ban-types': 'warn',
    '@typescript-eslint/ban-ts-comment': 'warn',
    '@typescript-eslint/explicit-member-accessibility': 'warn',
    '@typescript-eslint/no-empty-function': 'warn',
    '@typescript-eslint/no-shadow': 'warn',
    '@typescript-eslint/no-inferrable-types': 'warn',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/no-non-null-assertion': 'off',
    '@typescript-eslint/no-implied-eval': 'off',
    '@typescript-eslint/no-unused-vars': 'off',
    // unicorn
    'unicorn/no-object-as-default-parameter': 'warn',
    'unicorn/no-fn-reference-in-iterator': 'warn',
    'unicorn/prefer-number-properties': 'warn',
    'unicorn/consistent-function-scoping': 'warn',
    'unicorn/explicit-length-check': 'warn',
    'unicorn/prefer-math-trunc': 'warn',
    'unicorn/no-useless-undefined': 'warn',
    'unicorn/prefer-ternary': 'warn',
    'unicorn/better-regex': 'warn',
    'unicorn/prefer-includes': 'warn',
    'unicorn/import-index': 'warn',
    'unicorn/no-unreadable-array-destructuring': 'warn',
    'unicorn/no-console-spaces': 'warn',
    'unicorn/escape-case': 'warn',
    'unicorn/no-nested-ternary': 'warn',
    'unicorn/prefer-optional-catch-binding': 'warn',
    'unicorn/no-array-reduce': 'warn',
    'unicorn/prefer-array-some': 'warn',
    'unicorn/no-array-for-each': 'warn',
    'unicorn/prefer-export-from': 'warn',
    'unicorn/no-new-array': 'warn',
    'unicorn/no-lonely-if': 'warn',
    'unicorn/consistent-destructuring': 'warn',
    'unicorn/numeric-separators-style': 'warn',
    'unicorn/prefer-array-index-of': 'warn',
    'unicorn/no-array-callback-reference': 'off',
    'unicorn/catch-error-name': 'off',
    'unicorn/filename-case': 'off',
    'unicorn/no-null': 'off',
    'unicorn/no-reduce': 'off',
    'unicorn/number-literal-case': 'off',
    'unicorn/prefer-spread': 'off',
    'unicorn/prevent-abbreviations': 'off',
    // react
    'react/jsx-wrap-multilines': 'error',
    'react/self-closing-comp': 'error',
    'react/jsx-closing-bracket-location': 'error',
    'react/jsx-closing-tag-location': 'error',
    'react/no-unescaped-entities': 'warn',
    'react/jsx-curly-brace-presence': [
      'warn',
      { props: 'never', children: 'never' },
    ],
    'react/display-name': 'off',
    'react/jsx-boolean-value': 'off',
    'react/jsx-uses-react': 'off', //https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#eslint
    'react/react-in-jsx-scope': 'off', //https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#eslint
    // testing-library
    'testing-library/prefer-screen-queries': 'warn',
    'testing-library/no-node-access': 'warn',
    'testing-library/no-container': 'warn',
    'testing-library/no-node-access': 'warn',
    'testing-library/no-render-in-setup': 'warn',
    'testing-library/prefer-presence-queries': 'warn',
  },
}
